controller: joint_position_controller
robot_hardware:
  baud_rate: 250000
  min_motor_id: 0
  max_motor_id: 25
  joints_params:
    joint_0:
      name: joint_0
      origin: 2048
      min: 342
      max: 3754
      speed: 300
      acceleration: 30

    joint_1:
      name: joint_1
      origin: 2048
      min: 853
      max: 3243
      speed: 300
      acceleration: 30
    
    joint_2:
      name: joint_2
      origin: 2048
      min: 342
      max: 3754
      speed: 300
      acceleration: 30

    joint_3:
      name: joint_3
      origin: 2048
      min: 853
      max: 3243
      speed: 300
      acceleration: 30

    joint_4:
      name: joint_4
      origin: 2048
      min: 853
      max: 3243
      speed: 300
      acceleration: 30

    joint_5:
      name: joint_5
      origin: 2048
      min: 853
      max: 3243
      speed: 300
      acceleration: 30

    joint_6:
      name: joint_6
      origin: 2048
      min: 342
      max: 3754
      speed: 300
      acceleration: 30
  