config:
  comms:
    usb_device: "1a86:7523"
    baudrate: 250000

  servo_params:
    joint_0:
      name: shoulder_1
      origin: 2048
      min: 342
      max: 3754
      speed: 300
      acceleration: 30
    joint_1:
      name: shoulder_2
      origin: 2120
      min: 853
      max: 3243
      speed: 300
      acceleration: 20
    joint_2:
      name: elbow_1
      origin: 2048
      min: 342
      max: 3754
      speed: 300
      acceleration: 20
    joint_3:
      name: elbow_2
      origin: 2068
      min: 853
      max: 3243
      speed: 300
      acceleration: 20
    joint_4:
      name: wrist_1
      origin: 2048
      min: 853
      max: 3243
      speed: 300
      acceleration: 20
    joint_5:
      name: wrist_2
      origin: 2048
      min: 853
      max: 3243
      speed: 300
      acceleration: 20
    joint_6:
      name: wrist_3
      origin: 2048
      min: 342
      max: 3754
      speed: 300
      acceleration: 20

    gripper:
      name: gripper
      min: 200
      max: 500
      speed: 300
      distance: 0.0285
